node {
    docker.image('python:2-alpine') {
        stage('Build') {
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
    }
    docker.image(image 'qnib/pytest'){
        stage('Test') {
            steps {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
                }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
    docker.image('cdrx/pyinstaller-linux:python2') {
        stage('Deliver') {
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}
